import json
import pandas as pd
from fpdf import FPDF
from datetime import datetime
from urllib.parse import urlparse

SEVERITY_COLORS = {
    "CRITICAL": (192, 57, 43),
    "HIGH":     (230, 126, 34),
    "MEDIUM":   (243, 156, 18),
    "LOW":      (39, 174, 96),
}

def clean_text(text: str) -> str:
    """Replace special unicode characters that FPDF cannot encode."""
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        '\u2014': '-',   '\u2013': '-',   '\u2018': "'",
        '\u2019': "'",   '\u201c': '"',   '\u201d': '"',
        '\u2026': '...', '\u00a0': ' ',   '\u2022': '-',
        '\u00e9': 'e',   '\u00e0': 'a',
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text.encode('latin-1', errors='replace').decode('latin-1')


class PDF(FPDF):
    def header(self):
        self.set_fill_color(22, 33, 62)
        self.rect(0, 0, 210, 18, 'F')
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(255, 255, 255)
        self.set_y(5)
        self.cell(0, 8, "Access Control Security Report", align="C")
        self.set_text_color(0, 0, 0)
        self.ln(16)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Auto-generated by WebCrawler Framework", align="C")

    def section_title(self, title):
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(15, 52, 96)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, "  " + clean_text(title), ln=True, fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def key_value(self, key, value, bg=False):
        if bg:
            self.set_fill_color(245, 245, 245)
        else:
            self.set_fill_color(255, 255, 255)
        self.set_font("Helvetica", "B", 9)
        self.cell(40, 6, clean_text(key), fill=True)
        self.set_font("Helvetica", "", 9)
        self.multi_cell(0, 6, clean_text(str(value)), fill=True)


def generate_recommendations(violations: list) -> list:
    if not violations:
        return []

    try:
        df = pd.read_excel("Recommendations.xlsx", sheet_name="Recommendations")
    except FileNotFoundError:
        print("  WARNING: Recommendations.xlsx not found. Run update_recommendations.py first.")
        return []

    # Map violation types produced by cross_examine.py to the OWASP
    # categories present in the Recommendations spreadsheet.
    TYPE_MAP = {
        "VERTICAL_PE":      "BROKEN_ACCESS_CONTROL",
        "IDOR_HORIZONTAL":  "BROKEN_ACCESS_CONTROL",
    }

    recommendations = []

    for v in violations:
        raw_url = v.get("url", "")
        owner   = v.get("owner_role", "")
        tester  = v.get("tester_role", "")
        vtype   = v.get("violation_type", "")

        # Fall back via explicit map, then try stripping a MUTATION_ prefix
        lookup_type = TYPE_MAP.get(vtype, vtype)
        if lookup_type == vtype and vtype.startswith("MUTATION_"):
            lookup_type = "BROKEN_ACCESS_CONTROL"

        matches = df[df["violation_type"] == lookup_type]

        if matches.empty:
            print(f"  WARNING: No recommendations found for violation type '{vtype}' in Excel.")
            continue

        matched_row = None
        for _, row in matches.iterrows():
            keyword = str(row["keyword"]).lower()
            if keyword != "default" and keyword in raw_url.lower():
                matched_row = row
                break

        if matched_row is None:
            default_rows = matches[matches["keyword"] == "default"]
            if not default_rows.empty:
                matched_row = default_rows.iloc[0]

        if matched_row is not None:
            recommendation_text = matched_row["recommendation"]
            detail = (
                f"{recommendation_text} "
                f"(Affected endpoint: '{raw_url}', "
                f"accessed by role '{tester}' - should be restricted to '{owner}' only.)"
            )
            recommendations.append(clean_text(detail))

    return recommendations


def owasp_risk_rating(likelihood_score: float, impact_score: float) -> tuple:
    """
    Calculate OWASP Risk Rating based on likelihood and impact scores (1-9).
    Returns (risk_level, color_tuple).
    Reference: https://owasp.org/www-community/OWASP_Risk_Rating_Methodology
    """
    def band(score):
        if score <= 3:   return "LOW"
        elif score <= 6: return "MEDIUM"
        else:            return "HIGH"

    matrix = {
        ("HIGH",   "HIGH"):   ("CRITICAL", (192, 57,  43)),
        ("HIGH",   "MEDIUM"): ("HIGH",     (230, 126, 34)),
        ("HIGH",   "LOW"):    ("MEDIUM",   (243, 156, 18)),
        ("MEDIUM", "HIGH"):   ("HIGH",     (230, 126, 34)),
        ("MEDIUM", "MEDIUM"): ("MEDIUM",   (243, 156, 18)),
        ("MEDIUM", "LOW"):    ("LOW",      (39,  174, 96)),
        ("LOW",    "HIGH"):   ("MEDIUM",   (243, 156, 18)),
        ("LOW",    "MEDIUM"): ("LOW",      (39,  174, 96)),
        ("LOW",    "LOW"):    ("NOTE",     (149, 165, 166)),
    }
    return matrix.get((band(likelihood_score), band(impact_score)), ("NOTE", (149, 165, 166)))


def draw_security_score(pdf, violations, summary):
    """
    Display OWASP Risk Rating per violation and an overall risk summary.
    Likelihood is derived from confidence field (1-9).
    Impact is derived from severity field (1-9).
    """
    # Confidence → Likelihood score (1-9)
    likelihood_map = {"high": 7.5, "medium": 4.5, "low": 1.5}

    # Severity → Impact score (1-9)
    impact_map = {"CRITICAL": 9.0, "HIGH": 7.0, "MEDIUM": 4.5, "LOW": 2.0}

    pdf.section_title("OWASP Risk Rating")

    # Methodology note
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5,
        "Based on OWASP Risk Rating Methodology. Risk Score = Likelihood x Impact. "
        "Likelihood derived from confidence level. Impact derived from severity level.",
        ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # ── Per-violation risk rating table ──
    col_widths = [55, 30, 25, 25, 30]
    headers    = ["Endpoint", "Likelihood (1-9)", "Impact (1-9)", "Risk Score", "OWASP Rating"]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(22, 33, 62)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(headers, col_widths):
        pdf.cell(w, 7, h, border=1, fill=True, align="C")
    pdf.ln()
    pdf.set_text_color(0, 0, 0)

    risk_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "NOTE": 0}

    for i, v in enumerate(violations):
        confidence = v.get("confidence", "low").lower()
        severity   = v.get("severity",   "LOW").upper()

        l_score    = likelihood_map.get(confidence, 1.5)
        i_score    = impact_map.get(severity, 2.0)
        risk_score = round(l_score * i_score, 2)

        risk_level, (r, g, b) = owasp_risk_rating(l_score, i_score)
        risk_counts[risk_level] = risk_counts.get(risk_level, 0) + 1

        # Shorten URL for display
        url  = v.get("url", "")
        path = url.split("vulnweb.com")[-1] if "vulnweb.com" in url else url
        if len(path) > 32:
            path = path[:29] + "..."

        row_fill = (245, 245, 245) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*row_fill)
        pdf.set_font("Helvetica", "", 8)
        pdf.cell(col_widths[0], 6, clean_text(path),                    border=1, fill=True)
        pdf.cell(col_widths[1], 6, f"{confidence.title()} ({l_score})", border=1, fill=True, align="C")
        pdf.cell(col_widths[2], 6, f"{severity.title()} ({i_score})",   border=1, fill=True, align="C")
        pdf.cell(col_widths[3], 6, str(risk_score),                     border=1, fill=True, align="C")

        # Coloured OWASP rating cell
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(col_widths[4], 6, risk_level, border=1, fill=True, align="C")
        pdf.set_text_color(0, 0, 0)
        pdf.ln()

    pdf.ln(4)

    # ── Overall risk summary ──
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "Overall Risk Summary:", ln=True)

    summary_levels = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
    summary_colors = {
        "CRITICAL": (192, 57,  43),
        "HIGH":     (230, 126, 34),
        "MEDIUM":   (243, 156, 18),
        "LOW":      (39,  174, 96),
    }
    col_w = 40
    pdf.set_font("Helvetica", "B", 12)
    for level in summary_levels:
        r, g, b = summary_colors[level]
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(col_w, 14, str(risk_counts.get(level, 0)), border=1, fill=True, align="C")
    pdf.ln()
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(80, 80, 80)
    for level in summary_levels:
        pdf.cell(col_w, 5, level, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

    # ── OWASP Risk Matrix ──
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "OWASP Risk Rating Matrix (Likelihood x Impact):", ln=True)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 5, "Likelihood: Low=1-3, Medium=4-6, High=7-9  |  Impact: Low=1-3, Medium=4-6, High=7-9", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    matrix_labels = {
        ("HIGH",   "HIGH"):   ("CRITICAL", (192, 57,  43)),
        ("HIGH",   "MEDIUM"): ("HIGH",     (230, 126, 34)),
        ("HIGH",   "LOW"):    ("MEDIUM",   (243, 156, 18)),
        ("MEDIUM", "HIGH"):   ("HIGH",     (230, 126, 34)),
        ("MEDIUM", "MEDIUM"): ("MEDIUM",   (243, 156, 18)),
        ("MEDIUM", "LOW"):    ("LOW",      (39,  174, 96)),
        ("LOW",    "HIGH"):   ("MEDIUM",   (243, 156, 18)),
        ("LOW",    "MEDIUM"): ("LOW",      (39,  174, 96)),
        ("LOW",    "LOW"):    ("NOTE",     (149, 165, 166)),
    }

    cell_w      = 35
    cell_h      = 8
    impacts     = ["HIGH", "MEDIUM", "LOW"]
    likelihoods = ["HIGH", "MEDIUM", "LOW"]

    # Matrix header row
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(22, 33, 62)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(cell_w, cell_h, "Like \\ Impact", border=1, fill=True, align="C")
    for imp in impacts:
        pdf.cell(cell_w, cell_h, imp, border=1, fill=True, align="C")
    pdf.ln()

    for like in likelihoods:
        # Row label
        pdf.set_fill_color(15, 52, 96)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(cell_w, cell_h, like, border=1, fill=True, align="C")
        for imp in impacts:
            label, (r, g, b) = matrix_labels[(like, imp)]
            pdf.set_fill_color(r, g, b)
            pdf.set_text_color(255, 255, 255)
            pdf.set_font("Helvetica", "B", 7)
            pdf.cell(cell_w, cell_h, label, border=1, fill=True, align="C")
        pdf.set_text_color(0, 0, 0)
        pdf.ln()

    pdf.ln(4)


def generate_pdf(base_url, json_path="access_control_report.json", output_path=None):
    with open(json_path) as f:
        data = json.load(f)

    summary     = data["summary"]
    violations  = data["violations"]
    all_results = data["all_results"]

    if output_path is None:
        parsed_url = urlparse(base_url)
        domain     = parsed_url.netloc or parsed_url.path.split('/')[0]
        domain     = domain.replace('www.', '')
        output_path = f"report_for_{domain}.pdf"

    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Subtitle ──
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, clean_text(f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}   |   Target: {base_url}"), align="C", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── Executive Summary ──
    pdf.section_title("Executive Summary")
    stats = [
        ("Total Tests",      summary["total_tests"]),
        ("Total Violations", summary["total_violations"]),
        ("Critical",         summary["by_severity"]["CRITICAL"]),
        ("High",             summary["by_severity"]["HIGH"]),
        ("Medium",           summary["by_severity"]["MEDIUM"]),
        ("Low",              summary["by_severity"]["LOW"]),
    ]
    col_w = 32
    pdf.set_font("Helvetica", "B", 9)
    for label, val in stats:
        pdf.set_fill_color(230, 236, 255)
        pdf.cell(col_w, 12, str(val), align="C", fill=True, border=1)
    pdf.ln()
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(80, 80, 80)
    for label, val in stats:
        pdf.cell(col_w, 5, label, align="C")
    pdf.ln(10)
    pdf.set_text_color(0, 0, 0)

    # ── Roles Tested ──
    pdf.section_title("Roles Tested")
    headers    = ["Role", "Username", "Pages Crawled", "URLs Accessible", "APIs Found"]
    col_widths = [30, 35, 38, 42, 30]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(22, 33, 62)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(headers, col_widths):
        pdf.cell(w, 7, h, border=1, fill=True)
    pdf.ln()
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(0, 0, 0)
    for i, r in enumerate(summary["roles_tested"]):
        pdf.set_fill_color(240, 248, 255) if i % 2 == 0 else pdf.set_fill_color(255, 255, 255)
        for val, w in zip([r["role"], r["username"] or "-", r["pages_crawled"], r["urls_accessible"], r["apis_found"]], col_widths):
            pdf.cell(w, 6, clean_text(str(val)), border=1, fill=True)
        pdf.ln()
    pdf.ln(4)

    # ── Violations ──
    pdf.section_title(f"Detected Violations ({len(violations)})")
    for i, v in enumerate(violations, 1):
        sev     = v["severity"]
        r, g, b = SEVERITY_COLORS.get(sev, (100, 100, 100))
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, clean_text(f"  Violation #{i}  |  {sev}  |  {v['violation_type']}"), ln=True, fill=True)
        pdf.set_text_color(0, 0, 0)
        fields = [
            ("URL",         v["url"]),
            ("Owner Role",  v["owner_role"]),
            ("Tester Role", v["tester_role"]),
            ("HTTP Status", v["status_code"]),
            ("Confidence",  v["confidence"].upper()),
            ("Note",        v.get("note", "")),
        ]
        for j, (k, val) in enumerate(fields):
            pdf.key_value(k, val, bg=(j % 2 == 0))
        pdf.ln(4)

    # ── OWASP Risk Rating ──
    draw_security_score(pdf, violations, summary)

    # ── All Results ──
    pdf.section_title("All Test Results")
    headers2    = ["URL", "Owner", "Tester", "Status", "Access", "Confidence"]
    col_widths2 = [75, 22, 22, 18, 18, 25]
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(22, 33, 62)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(headers2, col_widths2):
        pdf.cell(w, 7, h, border=1, fill=True)
    pdf.ln()
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(0, 0, 0)
    for i, r in enumerate(all_results):
        if r["access_granted"]:
            pdf.set_fill_color(255, 230, 220)
        elif i % 2 == 0:
            pdf.set_fill_color(249, 249, 249)
        else:
            pdf.set_fill_color(255, 255, 255)
        url = clean_text(r["url"])
        if len(url) > 48:
            url = url[:45] + "..."
        row = [url, r["owner_role"], r["tester_role"], str(r["status_code"]),
               "Yes" if r["access_granted"] else "No", r["confidence"].upper()]
        for val, w in zip(row, col_widths2):
            pdf.cell(w, 6, clean_text(str(val)), border=1, fill=True)
        pdf.ln()
    pdf.ln(4)

    # ── Recommendations ──
    recommendations = generate_recommendations(violations)
    pdf.section_title(f"Recommendations ({len(recommendations)})")
    if not recommendations:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 6, "No violations found - no recommendations needed.", ln=True)
        pdf.set_text_color(0, 0, 0)
    else:
        for j, detail in enumerate(recommendations):
            pdf.set_font("Helvetica", "", 9)
            pdf.set_fill_color(240, 240, 255) if j % 2 == 0 else pdf.set_fill_color(255, 255, 255)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(5, 5, "", fill=True)
            pdf.multi_cell(0, 5, clean_text(f"{j+1}. {detail}"), fill=True)
            pdf.set_text_color(0, 0, 0)
            pdf.ln(2)

    pdf.output(output_path)
    print(f"PDF report saved to {output_path}")